export interface Category {
  id: string;
  en: string;
  hi: string;
  icon: string;
}

export const categories: Category[] = [
  { id: 'ac-repair', en: 'AC Repair & Service', hi: 'एसी रिपेयर और सर्विस', icon: '❄️' },
  { id: 'accountant', en: 'Accountant / CA', hi: 'अकाउंटेंट / सीए', icon: '📊' },
  { id: 'advocate', en: 'Advocate / Lawyer', hi: 'वकील / एडवोकेट', icon: '⚖️' },
  { id: 'ambulance', en: 'Ambulance Service', hi: 'एम्बुलेंस सेवा', icon: '🚑' },
  { id: 'architect', en: 'Architect', hi: 'आर्किटेक्ट', icon: '📐' },
  { id: 'astrologer', en: 'Astrologer / Jyotish', hi: 'ज्योतिषी / पंडित', icon: '🔮' },
  { id: 'auto-rickshaw', en: 'Auto Rickshaw Service', hi: 'ऑटो रिक्शा सेवा', icon: '🛺' },
  { id: 'ayurveda', en: 'Ayurveda & Naturopathy', hi: 'आयुर्वेद और नैचुरोपैथी', icon: '🌿' },
  { id: 'bakery', en: 'Bakery & Confectionery', hi: 'बेकरी और कन्फेक्शनरी', icon: '🍞' },
  { id: 'balloon-decor', en: 'Balloon & Party Decoration', hi: 'बैलून और पार्टी डेकोरेशन', icon: '🎈' },
  { id: 'band-baja', en: 'Band & DJ Services', hi: 'बैंड बाजा और डीजे सर्विस', icon: '🎺' },
  { id: 'barber', en: 'Barber / Men\'s Salon', hi: 'नाई / पुरुष सैलून', icon: '💈' },
  { id: 'battery-shop', en: 'Battery Shop', hi: 'बैटरी शॉप', icon: '🔋' },
  { id: 'beauty-parlour', en: 'Beauty Parlour / Women\'s Salon', hi: 'ब्यूटी पार्लर / महिला सैलून', icon: '💅' },
  { id: 'bicycle-repair', en: 'Bicycle Repair & Sales', hi: 'साइकिल रिपेयर और बिक्री', icon: '🚲' },
  { id: 'bike-mechanic', en: 'Bike & Motorcycle Mechanic', hi: 'बाइक और मोटरसाइकिल मैकेनिक', icon: '🏍️' },
  { id: 'blood-bank', en: 'Blood Bank', hi: 'ब्लड बैंक', icon: '🩸' },
  { id: 'book-shop', en: 'Book Shop & Stationery', hi: 'बुक शॉप और स्टेशनरी', icon: '📚' },
  { id: 'bore-well', en: 'Bore Well & Drilling', hi: 'बोरवेल और ड्रिलिंग', icon: '🕳️' },
  { id: 'boutique', en: 'Boutique & Designer Wear', hi: 'बुटीक और डिज़ाइनर वियर', icon: '👗' },
  { id: 'building-material', en: 'Building Material Supply', hi: 'बिल्डिंग मटेरियल सप्लाई', icon: '🧱' },
  { id: 'bus-travel', en: 'Bus & Travel Agent', hi: 'बस और ट्रैवल एजेंट', icon: '🚌' },
  { id: 'cable-tv', en: 'Cable TV & DTH Service', hi: 'केबल टीवी और डीटीएच सर्विस', icon: '📺' },
  { id: 'cake-shop', en: 'Cake & Pastry Shop', hi: 'केक और पेस्ट्री शॉप', icon: '🎂' },
  { id: 'car-mechanic', en: 'Car Mechanic / Garage', hi: 'कार मैकेनिक / गैराज', icon: '🔧' },
  { id: 'car-wash', en: 'Car Wash & Detailing', hi: 'कार वॉश और डिटेलिंग', icon: '🚗' },
  { id: 'carpenter', en: 'Carpenter & Woodwork', hi: 'बढ़ई / कारपेंटर', icon: '🪚' },
  { id: 'catering', en: 'Catering Service', hi: 'केटरिंग सर्विस', icon: '🍽️' },
  { id: 'cctv', en: 'CCTV & Security Systems', hi: 'सीसीटीवी और सिक्योरिटी सिस्टम', icon: '📹' },
  { id: 'cement-shop', en: 'Cement & Construction Supply', hi: 'सीमेंट और कंस्ट्रक्शन सप्लाई', icon: '🏗️' },
  { id: 'chai-stall', en: 'Tea Stall / Tea Vendor', hi: 'चाय की दुकान / चाय विक्रेता', icon: '☕' },
  { id: 'chemist', en: 'Chemist / Medical Store', hi: 'केमिस्ट / मेडिकल स्टोर', icon: '💊' },
  { id: 'chicken-meat', en: 'Chicken & Meat Shop', hi: 'चिकन और मीट शॉप', icon: '🍗' },
  { id: 'civil-contractor', en: 'Civil Contractor', hi: 'सिविल कॉन्ट्रैक्टर', icon: '👷' },
  { id: 'cloth-shop', en: 'Cloth & Fabric Shop', hi: 'कपड़ा और फैब्रिक दुकान', icon: '🧵' },
  { id: 'coaching', en: 'Coaching & Tuition Center', hi: 'कोचिंग और ट्यूशन सेंटर', icon: '📝' },
  { id: 'cobbler', en: 'Shoe Repair & Cobbler', hi: 'जूता रिपेयर / मोची', icon: '👞' },
  { id: 'coconut-vendor', en: 'Coconut Water Vendor', hi: 'नारियल पानी विक्रेता', icon: '🥥' },
  { id: 'computer-repair', en: 'Computer Repair & Service', hi: 'कंप्यूटर रिपेयर और सर्विस', icon: '💻' },
  { id: 'construction', en: 'Construction & Labour Service', hi: 'कंस्ट्रक्शन और लेबर सर्विस', icon: '🏛️' },
  { id: 'courier', en: 'Courier & Delivery Service', hi: 'कूरियर और डिलीवरी सर्विस', icon: '📦' },
  { id: 'crockery', en: 'Crockery & Utensils Shop', hi: 'बर्तन और क्रॉकरी दुकान', icon: '🍶' },
  { id: 'cyber-cafe', en: 'Cyber Cafe & Printing', hi: 'साइबर कैफे और प्रिंटिंग', icon: '🖨️' },
  { id: 'dairy', en: 'Dairy & Milk Products', hi: 'डेयरी और दूध उत्पाद', icon: '🥛' },
  { id: 'dance-class', en: 'Dance Class & Academy', hi: 'डांस क्लास और अकादमी', icon: '💃' },
  { id: 'dentist', en: 'Dentist / Dental Clinic', hi: 'दंत चिकित्सक / डेंटल क्लिनिक', icon: '🦷' },
  { id: 'dhaba', en: 'Dhaba & Restaurant', hi: 'ढाबा और रेस्टोरेंट', icon: '🍛' },
  { id: 'laundry', en: 'Laundry & Washing Service', hi: 'लॉन्ड्री और धुलाई सर्विस', icon: '👔' },
  { id: 'diagnostic-center', en: 'Diagnostic Center & Lab', hi: 'डायग्नोस्टिक सेंटर और लैब', icon: '🔬' },
  { id: 'dietitian', en: 'Dietitian & Nutritionist', hi: 'डाइटीशियन और न्यूट्रिशनिस्ट', icon: '🥗' },
  { id: 'digital-marketing', en: 'Digital Marketing Agency', hi: 'डिजिटल मार्केटिंग एजेंसी', icon: '📱' },
  { id: 'doctor', en: 'Doctor / Clinic', hi: 'डॉक्टर / क्लिनिक', icon: '🏥' },
  { id: 'driving-school', en: 'Driving School', hi: 'ड्राइविंग स्कूल', icon: '🚘' },
  { id: 'dry-cleaner', en: 'Dry Cleaning Service', hi: 'ड्राई क्लीनिंग सर्विस', icon: '🧹' },
  { id: 'egg-vendor', en: 'Egg & Poultry Vendor', hi: 'अंडा और पोल्ट्री विक्रेता', icon: '🥚' },
  { id: 'electrical-shop', en: 'Electrical Equipment Shop', hi: 'इलेक्ट्रिकल उपकरण दुकान', icon: '💡' },
  { id: 'electrician', en: 'Electrician', hi: 'इलेक्ट्रीशियन / बिजली मिस्त्री', icon: '⚡' },
  { id: 'electronics-repair', en: 'Electronics Repair', hi: 'इलेक्ट्रॉनिक्स रिपेयर', icon: '🔌' },
  { id: 'embroidery', en: 'Embroidery & Zari Work', hi: 'एम्ब्रॉयडरी और ज़री वर्क', icon: '🪡' },
  { id: 'emitra', en: 'E-Mitra / CSC / Jan Seva Kendra', hi: 'ई-मित्र / सीएससी / जन सेवा केंद्र', icon: '🏛️' },
  { id: 'event-manager', en: 'Event Management Company', hi: 'इवेंट मैनेजमेंट कंपनी', icon: '🎪' },
  { id: 'eye-doctor', en: 'Eye Doctor / Ophthalmologist', hi: 'आँखों का डॉक्टर / नेत्र चिकित्सक', icon: '👁️' },
  { id: 'fabricator', en: 'Fabrication & Welding', hi: 'फैब्रिकेशन और वेल्डिंग', icon: '🔩' },
  { id: 'fast-food', en: 'Fast Food & Snacks', hi: 'फास्ट फूड और स्नैक्स', icon: '🍔' },
  { id: 'fertilizer', en: 'Fertilizer & Seed Shop', hi: 'खाद और बीज दुकान', icon: '🌾' },
  { id: 'fire-safety', en: 'Fire Safety Equipment', hi: 'फायर सेफ्टी उपकरण', icon: '🧯' },
  { id: 'fish-shop', en: 'Fish & Seafood Shop', hi: 'मछली और सीफूड दुकान', icon: '🐟' },
  { id: 'fitness-trainer', en: 'Fitness Trainer / Gym', hi: 'फिटनेस ट्रेनर / जिम', icon: '🏋️' },
  { id: 'florist', en: 'Florist & Flower Vendor', hi: 'फूल विक्रेता / फ्लोरिस्ट', icon: '💐' },
  { id: 'flour-mill', en: 'Flour Mill / Atta Chakki', hi: 'आटा चक्की', icon: '🌾' },
  { id: 'footwear', en: 'Footwear & Shoes Shop', hi: 'जूते-चप्पल दुकान', icon: '👟' },
  { id: 'freelance-writer', en: 'Freelance Writer & Content Creator', hi: 'फ्रीलांस लेखक और कंटेंट क्रिएटर', icon: '✍️' },
  { id: 'fruit-vendor', en: 'Fruit Vendor & Seller', hi: 'फल विक्रेता', icon: '🍎' },
  { id: 'furniture', en: 'Furniture Shop & Showroom', hi: 'फर्नीचर शॉप और शोरूम', icon: '🪑' },
  { id: 'garment-shop', en: 'Garment & Readymade Shop', hi: 'गारमेंट और रेडीमेड शॉप', icon: '👕' },
  { id: 'gas-agency', en: 'Gas Agency & Refill', hi: 'गैस एजेंसी और रीफिल', icon: '🔥' },
  { id: 'general-store', en: 'General Store / Kirana', hi: 'जनरल स्टोर / किराना', icon: '🏪' },
  { id: 'gift-shop', en: 'Gift Shop & Gallery', hi: 'गिफ्ट शॉप और गैलरी', icon: '🎁' },
  { id: 'glass-shop', en: 'Glass & Mirror Shop', hi: 'शीशा और ग्लास शॉप', icon: '🪞' },
  { id: 'graphic-designer', en: 'Graphic & UI Designer', hi: 'ग्राफिक और यूआई डिज़ाइनर', icon: '🎨' },
  { id: 'grocery', en: 'Grocery & Vegetable Store', hi: 'ग्रॉसरी और सब्ज़ी दुकान', icon: '🥬' },
  { id: 'gym', en: 'Gym & Health Club', hi: 'जिम और हेल्थ क्लब', icon: '💪' },
  { id: 'halwai', en: 'Sweet Shop & Confectioner', hi: 'हलवाई / मिठाई दुकान', icon: '🍬' },
  { id: 'hardware', en: 'Hardware & Tools Shop', hi: 'हार्डवेयर और टूल्स दुकान', icon: '🔨' },
  { id: 'home-appliance', en: 'Home Appliance Repair', hi: 'होम अप्लायंस रिपेयर', icon: '🏠' },
  { id: 'home-tutor', en: 'Home Tutor & Private Teacher', hi: 'होम ट्यूटर और प्राइवेट टीचर', icon: '🎓' },
  { id: 'hospital', en: 'Hospital & Nursing Home', hi: 'अस्पताल और नर्सिंग होम', icon: '🏥' },
  { id: 'hotel', en: 'Hotel & Lodge', hi: 'होटल और लॉज', icon: '🏨' },
  { id: 'house-painting', en: 'House Painting & Colour Service', hi: 'हाउस पेंटिंग और रंगाई', icon: '🖌️' },
  { id: 'ice-cream', en: 'Ice Cream & Kulfi Vendor', hi: 'आइसक्रीम और कुल्फी विक्रेता', icon: '🍦' },
  { id: 'insurance-agent', en: 'Insurance Agent & Advisor', hi: 'इंश्योरेंस एजेंट और सलाहकार', icon: '🛡️' },
  { id: 'interior-designer', en: 'Interior Designer & Decorator', hi: 'इंटीरियर डिज़ाइनर और डेकोरेटर', icon: '🛋️' },
  { id: 'inverter-ups', en: 'Inverter & UPS Service', hi: 'इन्वर्टर और यूपीएस सर्विस', icon: '🔌' },
  { id: 'ironing', en: 'Ironing & Press Service', hi: 'इस्त्री / प्रेस सर्विस', icon: '♨️' },
  { id: 'jewellery', en: 'Jewellery Shop & Goldsmith', hi: 'ज्वेलरी शॉप और सुनार', icon: '💍' },
  { id: 'juice-stall', en: 'Juice & Sugarcane Stall', hi: 'जूस और गन्ने का ठेला', icon: '🧃' },
  { id: 'key-maker', en: 'Key Maker & Locksmith', hi: 'चाबी बनाने वाला / लॉक स्मिथ', icon: '🔑' },
  { id: 'kiosk', en: 'Kiosk & Small Retail Stall', hi: 'कियोस्क और छोटी रिटेल दुकान', icon: '🏪' },
  { id: 'ladies-tailor', en: 'Ladies Tailor', hi: 'लेडीज़ टेलर', icon: '👗' },
  { id: 'laptop-repair', en: 'Laptop Repair & Service', hi: 'लैपटॉप रिपेयर और सर्विस', icon: '💻' },
  { id: 'led-lighting', en: 'LED & Lighting Solutions', hi: 'एलईडी और लाइटिंग सॉल्यूशन', icon: '💡' },
  { id: 'loan-agent', en: 'Loan Agent & Finance', hi: 'लोन एजेंट और फाइनेंस', icon: '💰' },
  { id: 'machine-repair', en: 'Machine Repair & Maintenance', hi: 'मशीन रिपेयर और रखरखाव', icon: '⚙️' },
  { id: 'maid-service', en: 'Maid & House Help Service', hi: 'घर सहायता सर्विस', icon: '🧹' },
  { id: 'makeup-artist', en: 'Makeup Artist & Beautician', hi: 'मेकअप आर्टिस्ट और ब्यूटीशियन', icon: '💄' },
  { id: 'manpower', en: 'Manpower & Staffing Service', hi: 'मैनपावर और स्टाफिंग सर्विस', icon: '👥' },
  { id: 'marble-tiles', en: 'Marble & Tiles Dealer', hi: 'मार्बल और टाइल्स डीलर', icon: '🏗️' },
  { id: 'mason', en: 'Mason & Bricklayer', hi: 'राज मिस्त्री / मेसन', icon: '🧱' },
  { id: 'massage-spa', en: 'Massage & Spa Center', hi: 'मसाज और स्पा सेंटर', icon: '💆' },
  { id: 'math-tutor', en: 'Math Tutor & Coach', hi: 'गणित शिक्षक', icon: '📐' },
  { id: 'mehndi', en: 'Mehndi & Henna Artist', hi: 'मेहंदी कलाकार', icon: '🤲' },
  { id: 'mobile-repair', en: 'Mobile Repair & Accessories', hi: 'मोबाइल रिपेयर और एक्सेसरीज', icon: '📱' },
  { id: 'mobile-recharge', en: 'Mobile Recharge & SIM Service', hi: 'मोबाइल रिचार्ज और सिम सर्विस', icon: '📲' },
  { id: 'money-transfer', en: 'Money Transfer & Banking Agent', hi: 'मनी ट्रांसफर और बैंकिंग एजेंट', icon: '💸' },
  { id: 'music-teacher', en: 'Music Teacher & Instrument Classes', hi: 'संगीत शिक्षक और वाद्य कक्षाएं', icon: '🎵' },
  { id: 'newspaper', en: 'Newspaper & Magazine Vendor', hi: 'अखबार और पत्रिका विक्रेता', icon: '📰' },
  { id: 'nursing', en: 'Nursing & Home Healthcare', hi: 'नर्सिंग और होम हेल्थकेयर', icon: '👩‍⚕️' },
  { id: 'opticals', en: 'Optical & Spectacles Shop', hi: 'ऑप्टिकल और चश्मे की दुकान', icon: '👓' },
  { id: 'packers-movers', en: 'Packers & Movers', hi: 'पैकर्स और मूवर्स', icon: '📦' },
  { id: 'paint-shop', en: 'Paint & Colour Shop', hi: 'पेंट और रंग दुकान', icon: '🎨' },
  { id: 'paan-shop', en: 'Paan & Betel Shop', hi: 'पान की दुकान', icon: '🌿' },
  { id: 'pandit', en: 'Pandit & Puja Services', hi: 'पंडित और पूजा सर्विस', icon: '🙏' },
  { id: 'passport-visa', en: 'Passport & Visa Agent', hi: 'पासपोर्ट और वीज़ा एजेंट', icon: '🛂' },
  { id: 'pathology', en: 'Pathology & Diagnostic Lab', hi: 'पैथोलॉजी और डायग्नोस्टिक लैब', icon: '🧪' },
  { id: 'pest-control', en: 'Pest Control Service', hi: 'पेस्ट कंट्रोल सर्विस', icon: '🐛' },
  { id: 'pet-shop', en: 'Pet Shop & Veterinary', hi: 'पेट शॉप और पशु डॉक्टर', icon: '🐾' },
  { id: 'petrol-pump', en: 'Petrol Pump & Fuel Station', hi: 'पेट्रोल पंप और ईंधन स्टेशन', icon: '⛽' },
  { id: 'photo-studio', en: 'Photo Studio & Photography', hi: 'फोटो स्टूडियो और फोटोग्राफी', icon: '📸' },
  { id: 'physiotherapy', en: 'Physiotherapy Clinic', hi: 'फिज़ियोथेरेपी क्लिनिक', icon: '🦴' },
  { id: 'plumber', en: 'Plumber & Pipe Fitting', hi: 'प्लंबर / नलकार', icon: '🚿' },
  { id: 'pooja-samagri', en: 'Pooja Samagri & Religious Items', hi: 'पूजा सामग्री और धार्मिक सामान', icon: '🪔' },
  { id: 'property-dealer', en: 'Property Dealer & Real Estate', hi: 'प्रॉपर्टी डीलर और रियल एस्टेट', icon: '🏘️' },
  { id: 'puncture', en: 'Puncture Repair & Tyre Service', hi: 'पंचर रिपेयर और टायर सर्विस', icon: '🛞' },
  { id: 'raddiwala', en: 'Scrap Dealer & Recycling', hi: 'रद्दी/कबाड़ डीलर और रीसाइक्लिंग', icon: '♻️' },
  { id: 'ration-shop', en: 'Ration Shop & Fair Price Store', hi: 'राशन दुकान / उचित मूल्य दुकान', icon: '🛒' },
  { id: 'rental-service', en: 'Vehicle & Equipment Rental', hi: 'वाहन और उपकरण किराया', icon: '🚐' },
  { id: 'ro-repair', en: 'RO & Water Purifier Service', hi: 'आरओ और वॉटर प्यूरीफायर सर्विस', icon: '💧' },
  { id: 'sabzi-mandi', en: 'Vegetable Market & Mandi', hi: 'सब्ज़ी मंडी', icon: '🥕' },
  { id: 'sari-shop', en: 'Saree & Sari Shop', hi: 'साड़ी की दुकान', icon: '🥻' },
  { id: 'school', en: 'School & Play School', hi: 'स्कूल और प्ले स्कूल', icon: '🏫' },
  { id: 'scooter-repair', en: 'Scooter & Two-Wheeler Repair', hi: 'स्कूटर और दोपहिया रिपेयर', icon: '🛵' },
  { id: 'security-guard', en: 'Security Guard & Agency', hi: 'सिक्योरिटी गार्ड और एजेंसी', icon: '💂' },
  { id: 'sewing-machine', en: 'Sewing Machine Repair & Sales', hi: 'सिलाई मशीन रिपेयर और बिक्री', icon: '🧵' },
  { id: 'solar-panel', en: 'Solar Panel Installation', hi: 'सोलर पैनल इंस्टॉलेशन', icon: '☀️' },
  { id: 'spa-wellness', en: 'Spa & Wellness Center', hi: 'स्पा और वेलनेस सेंटर', icon: '🧘' },
  { id: 'spoken-english', en: 'Spoken English & Language Class', hi: 'स्पोकन इंग्लिश और भाषा कक्षा', icon: '🗣️' },
  { id: 'sports-shop', en: 'Sports & Games Shop', hi: 'खेल और गेम्स शॉप', icon: '🏏' },
  { id: 'steel-almirah', en: 'Steel Almirah & Metal Furniture', hi: 'स्टील अलमारी और मेटल फर्नीचर', icon: '🗄️' },
  { id: 'sweet-shop', en: 'Sweet Shop & Mithai', hi: 'मिठाई दुकान', icon: '🍯' },
  { id: 'tailor', en: 'Tailor & Stitching Service', hi: 'टेलर / दर्ज़ी / सिलाई सर्विस', icon: '✂️' },
  { id: 'tanker-water', en: 'Water Tanker Service', hi: 'वॉटर टैंकर सर्विस', icon: '🚰' },
  { id: 'tattoo-artist', en: 'Tattoo Artist & Studio', hi: 'टैटू आर्टिस्ट और स्टूडियो', icon: '🎭' },
  { id: 'taxi-cab', en: 'Taxi & Cab Service', hi: 'टैक्सी और कैब सर्विस', icon: '🚕' },
  { id: 'tea-spice', en: 'Tea & Spice Vendor', hi: 'चाय और मसाला विक्रेता', icon: '🫖' },
  { id: 'teacher', en: 'Teacher & Educator', hi: 'शिक्षक और एजुकेटर', icon: '👩‍🏫' },
  { id: 'technician', en: 'General Technician', hi: 'जनरल टेक्नीशियन', icon: '🔧' },
  { id: 'tent-house', en: 'Tent House & Shamiyana', hi: 'टेंट हाउस और शामियाना', icon: '⛺' },
  { id: 'tiffin-service', en: 'Tiffin & Dabba Service', hi: 'टिफिन और डब्बा सर्विस', icon: '🍱' },
  { id: 'tiles-fitter', en: 'Tiles Fitting & Floor Work', hi: 'टाइल्स फिटिंग और फ्लोर वर्क', icon: '🔲' },
  { id: 'towing', en: 'Towing & Breakdown Service', hi: 'टोइंग और ब्रेकडाउन सर्विस', icon: '🚨' },
  { id: 'toy-shop', en: 'Toy & Kids Shop', hi: 'खिलौने और बच्चों की दुकान', icon: '🧸' },
  { id: 'transport', en: 'Transport & Logistics', hi: 'ट्रांसपोर्ट और लॉजिस्टिक्स', icon: '🚛' },
  { id: 'travel-agent', en: 'Travel Agent & Tour Operator', hi: 'ट्रैवल एजेंट और टूर ऑपरेटर', icon: '✈️' },
  { id: 'tubewell', en: 'Tubewell & Handpump Repair', hi: 'ट्यूबवेल और हैंडपंप रिपेयर', icon: '🛠️' },
  { id: 'tv-repair', en: 'TV Repair & Service', hi: 'टीवी रिपेयर और सर्विस', icon: '📺' },
  { id: 'tyre-shop', en: 'Tyre Shop & Alignment', hi: 'टायर शॉप और अलाइनमेंट', icon: '🛞' },
  { id: 'unani-medicine', en: 'Unani & Herbal Medicine', hi: 'यूनानी और हर्बल दवा', icon: '🌱' },
  { id: 'vegetable-vendor', en: 'Vegetable Vendor & Cart', hi: 'सब्ज़ी विक्रेता', icon: '🥦' },
  { id: 'veterinary', en: 'Veterinary Doctor', hi: 'पशु चिकित्सक', icon: '🐄' },
  { id: 'video-editor', en: 'Video Editor & YouTuber', hi: 'वीडियो एडिटर और यूट्यूबर', icon: '🎬' },
  { id: 'washing-machine', en: 'Washing Machine Repair', hi: 'वॉशिंग मशीन रिपेयर', icon: '🧺' },
  { id: 'water-supplier', en: 'Water Supplier & Jar Service', hi: 'पानी सप्लायर और जार सर्विस', icon: '🚰' },
  { id: 'web-developer', en: 'Web & App Developer', hi: 'वेब और ऐप डेवलपर', icon: '🌐' },
  { id: 'wedding-planner', en: 'Wedding Planner & Services', hi: 'वेडिंग प्लानर और सर्विसेज', icon: '💒' },
  { id: 'xerox-shop', en: 'Xerox & Photocopy Shop', hi: 'ज़ेरॉक्स और फोटोकॉपी शॉप', icon: '📄' },
  { id: 'yoga-teacher', en: 'Yoga Teacher & Instructor', hi: 'योग शिक्षक और प्रशिक्षक', icon: '🧘‍♂️' },
  // === Street Vendors, Cart Businesses, Mobile Sellers ===
  { id: 'street-food', en: 'Street Food & Chaat Vendor', hi: 'स्ट्रीट फूड और चाट विक्रेता', icon: '🍢' },
  { id: 'cart-vendor', en: 'Cart & Thela Business', hi: 'ठेला और रेहड़ी व्यापार', icon: '🛒' },
  { id: 'mobile-hawker', en: 'Mobile Hawker & Feriwala', hi: 'फेरीवाला / हॉकर', icon: '🚶' },
  { id: 'bangle-seller', en: 'Bangle & Choodi Seller', hi: 'चूड़ी विक्रेता', icon: '💎' },
  { id: 'corn-seller', en: 'Corn & Roasted Bhutta Seller', hi: 'भुट्टा विक्रेता', icon: '🌽' },
  { id: 'cotton-candy', en: 'Cotton Candy & Candy Floss', hi: 'बुढ़िया के बाल / कैंडी फ्लॉस', icon: '🍭' },
  { id: 'earthenware-seller', en: 'Earthenware & Clay Pottery', hi: 'मिट्टी के बर्तन और कुम्हार', icon: '🏺' },
  { id: 'ice-gola', en: 'Ice Gola & Crushed Ice Vendor', hi: 'बर्फ का गोला विक्रेता', icon: '🧊' },
  { id: 'knife-sharpener', en: 'Knife & Scissors Sharpener', hi: 'चाकू और कैंची धार वाला', icon: '🔪' },
  { id: 'kulhad-chai', en: 'Kulhad Chai & Traditional Tea', hi: 'कुल्हड़ चाय विक्रेता', icon: '🍵' },
  { id: 'lassi-shakes', en: 'Lassi, Shakes & Juice Cart', hi: 'लस्सी, शेक और जूस रेहड़ी', icon: '🥤' },
  { id: 'mattress-maker', en: 'Mattress Maker & Gadda Service', hi: 'गद्दा बनाने वाला / रुई धुनाई', icon: '🛏️' },
  { id: 'momos-stall', en: 'Momos & Dimsum Stall', hi: 'मोमोज़ और डिमसम स्टॉल', icon: '🥟' },
  { id: 'peanut-seller', en: 'Peanut & Dry Snack Seller', hi: 'मूंगफली और सूखा नाश्ता विक्रेता', icon: '🥜' },
  { id: 'popcorn-seller', en: 'Popcorn & Makka Seller', hi: 'पॉपकॉर्न विक्रेता', icon: '🍿' },
  { id: 'shoe-polish', en: 'Shoe Polish & Care Service', hi: 'बूट पॉलिश सर्विस', icon: '👞' },
  { id: 'toy-hawker', en: 'Toy & Novelty Hawker', hi: 'खिलौना विक्रेता / हॉकर', icon: '🧸' },
  { id: 'dosa-stall', en: 'Dosa & South Indian Stall', hi: 'डोसा और साउथ इंडियन स्टॉल', icon: '🥞' },
  { id: 'paratha-stall', en: 'Paratha & Roti Stall', hi: 'पराठा और रोटी स्टॉल', icon: '🫓' },
  { id: 'samosa-stall', en: 'Samosa & Pakoda Stall', hi: 'समोसा और पकौड़ा स्टॉल', icon: '🥘' },
  { id: 'sugarcane-juice', en: 'Sugarcane Juice Vendor', hi: 'गन्ने का रस विक्रेता', icon: '🥤' },
  // === Professional & Enterprise Categories ===
  { id: 'ecommerce', en: 'E-Commerce Company', hi: 'ई-कॉमर्स कंपनी', icon: '🛍️' },
  { id: 'logistics', en: 'Logistics & Supply Chain Company', hi: 'लॉजिस्टिक्स और सप्लाई चेन कंपनी', icon: '🚛' },
  { id: 'it-services', en: 'IT & Software Company', hi: 'आईटी और सॉफ्टवेयर कंपनी', icon: '🖥️' },
  { id: 'consulting', en: 'Business Consulting & Advisory', hi: 'बिज़नेस कंसल्टिंग और सलाहकार', icon: '📋' },
  { id: 'manufacturing', en: 'Manufacturing Unit & Factory', hi: 'मैन्युफैक्चरिंग और फैक्ट्री', icon: '🏭' },
  { id: 'export-import', en: 'Export & Import Company', hi: 'निर्यात और आयात कंपनी', icon: '🚢' },
  { id: 'advertising', en: 'Advertising & Media Agency', hi: 'विज्ञापन और मीडिया एजेंसी', icon: '📺' },
  { id: 'ngo', en: 'NGO & Social Organization', hi: 'एनजीओ और सामाजिक संगठन', icon: '🤝' },
  { id: 'govt-office', en: 'Government Office & Department', hi: 'सरकारी कार्यालय और विभाग', icon: '🏛️' },
  { id: 'bank-finance', en: 'Bank & Financial Institution', hi: 'बैंक और वित्तीय संस्थान', icon: '🏦' },
  { id: 'telecom', en: 'Telecom & Internet Provider', hi: 'टेलीकॉम और इंटरनेट प्रोवाइडर', icon: '📡' },
  { id: 'hr-recruitment', en: 'HR & Recruitment Agency', hi: 'एचआर और भर्ती एजेंसी', icon: '🧑‍💼' },
  { id: 'marketing-agency', en: 'Marketing & PR Agency', hi: 'मार्केटिंग और पीआर एजेंसी', icon: '📣' },
  { id: 'startup', en: 'Startup & Innovation Company', hi: 'स्टार्टअप और इनोवेशन कंपनी', icon: '🚀' },
  { id: 'franchise', en: 'Franchise & Dealership', hi: 'फ्रैंचाइज़ी और डीलरशिप', icon: '🤝' },
  { id: 'warehouse', en: 'Warehouse & Godown', hi: 'गोदाम और वेयरहाउस', icon: '🏭' },
  { id: 'handicraft', en: 'Handicraft & Artisan Products', hi: 'हैंडीक्राफ्ट और कारीगर उत्पाद', icon: '🎎' },
  { id: 'aquarium-fish', en: 'Aquarium & Ornamental Fish', hi: 'एक्वेरियम और सजावटी मछली', icon: '🐠' },
  { id: 'paneer-dairy', en: 'Paneer & Dairy Products', hi: 'पनीर और डेयरी प्रोडक्ट', icon: '🧀' },
  { id: 'stitching-alteration', en: 'Stitching & Alteration Service', hi: 'सिलाई और अल्टरेशन सर्विस', icon: '🧵' },
  { id: 'pickup-delivery', en: 'Pickup & Delivery Service', hi: 'पिकअप और डिलीवरी सेवा', icon: '📦' },
  { id: 'waterproofing', en: 'Waterproofing Service', hi: 'वॉटरप्रूफिंग सर्विस', icon: '💧' },
  { id: 'astrology-kundli', en: 'Kundli & Horoscope Service', hi: 'कुंडली और जन्मपत्री सर्विस', icon: '🌟' },
  { id: 'translator', en: 'Translator & Interpreter', hi: 'अनुवादक और दुभाषिया', icon: '🗣️' },
  { id: 'wedding-decor', en: 'Wedding & Event Decoration', hi: 'शादी और इवेंट डेकोरेशन', icon: '💒' },
  { id: 'cycle-rickshaw', en: 'Cycle Rickshaw Service', hi: 'साइकिल रिक्शा सेवा', icon: '🚲' },
  { id: 'tent-rental', en: 'Tent & Chair Rental', hi: 'टेंट और कुर्सी किराया', icon: '🎪' },
  { id: 'flower-garland', en: 'Flower Garland & Mala Maker', hi: 'फूल माला बनाने वाला', icon: '💐' },
  { id: 'mobile-cover', en: 'Mobile Cover & Accessories', hi: 'मोबाइल कवर और एक्सेसरीज', icon: '📱' },
  { id: 'plastic-goods', en: 'Plastic & Household Goods', hi: 'प्लास्टिक और घरेलू सामान', icon: '🪣' },
  { id: 'photography-videography', en: 'Photography & Videography', hi: 'फोटोग्राफी और वीडियोग्राफी', icon: '📸' },
  { id: 'coaching-competitive', en: 'Competitive Exam Coaching', hi: 'प्रतियोगी परीक्षा कोचिंग', icon: '🏆' },
  { id: 'cleaning-service', en: 'Home & Office Cleaning Service', hi: 'घर और ऑफिस सफाई सर्विस', icon: '🧽' },
  { id: 'pest-termite', en: 'Termite & Pest Treatment', hi: 'दीमक और कीट उपचार', icon: '🪲' },
  { id: 'artists-performers', en: 'Artist & Performing Arts', hi: 'कलाकार और परफॉर्मिंग आर्ट्स', icon: '🎭' },
  { id: 'skill-training', en: 'Skill Training & Workshop', hi: 'कौशल प्रशिक्षण और कार्यशाला', icon: '🎯' },
  { id: 'organic-farming', en: 'Organic Farming & Products', hi: 'जैविक खेती और उत्पाद', icon: '🌱' },
  { id: 'home-nursing', en: 'Home Nursing & Patient Care', hi: 'होम नर्सिंग और रोगी देखभाल', icon: '🏥' },
  { id: 'ambulance-private', en: 'Private Ambulance Service', hi: 'निजी एम्बुलेंस सर्विस', icon: '🚑' },
  { id: 'ca-tax', en: 'CA, Tax & GST Service', hi: 'सीए, टैक्स और जीएसटी सर्विस', icon: '📊' },
  { id: 'coworking', en: 'Co-Working Space & Office', hi: 'को-वर्किंग स्पेस और ऑफिस', icon: '🏢' },
].sort((a, b) => a.en.localeCompare(b.en));

export const emergencyHelplines = [
  { name: 'Police', nameHi: 'पुलिस', number: '100', altNumber: '112', icon: '🚔' },
  { name: 'Emergency', nameHi: 'इमरजेंसी', number: '112', icon: '🆘' },
  { name: 'Ambulance', nameHi: 'एम्बुलेंस', number: '108', icon: '🚑' },
  { name: 'Fire Brigade', nameHi: 'फायर ब्रिगेड', number: '101', icon: '🚒' },
  { name: 'Women Helpline', nameHi: 'महिला हेल्पलाइन', number: '1091', icon: '👩' },
  { name: 'Child Helpline', nameHi: 'चाइल्ड हेल्पलाइन', number: '1098', icon: '👶' },
  { name: 'Disaster Mgmt', nameHi: 'आपदा प्रबंधन', number: '1078', icon: '⚠️' },
  { name: 'Senior Citizen', nameHi: 'वरिष्ठ नागरिक', number: '14567', icon: '👴' },
  { name: 'Anti-Poison', nameHi: 'एंटी-पॉइज़न', number: '1066', icon: '☠️' },
];
